[projects.hello-world]
git.repository = "https://github.com/sirikon/cow.git"
webhook.secret = "secret"
compose.project_path = "/src/example-compose-project"
compose.compose_files = [
    "docker/docker-compose.yml",
    "docker/docker-compose.extra.yml",
]
[projects.hello-world.compose.environment]
MESSAGE = "Hello! Cow seems to be working!"
