services:
  web:
    image: php:8.1-apache-bookworm
    restart: always
    volumes:
      - ${COW_PROJECT_PATH}/html:/var/www/html:ro
    environment:
      - MESSAGE=${MESSAGE}
    ports:
    - "9000:80"
